trigger:
- master
- develop
- rel/*
- preview/*

pr:
- master
- rel/*
- preview/*

jobs:
- job: Windows
  pool:
    vmImage: vs2017-win2016

  steps:
  - task: DotNetCoreInstaller@0
    displayName: Install Dot Net Core v2.2.1
    inputs:
        version: '2.2.103'
