version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.2-sdk
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
      - checkout
      - run: dotnet build ./IqOptionApi.Net.sln